// Original passages written for this game (not excerpts from real books/articles), styled
// like different genres so the "vandalize the paragraph" bit has room to be funny. Each has
// exactly 10 editable segments.
function seg(id, original) {
  return { type: 'editable', id, original }
}
function text(value) {
  return { type: 'text', value }
}

export const TEXTS = [
  {
    id: 'fairy-tale',
    parts: [
      text('Once upon a time, in a '),
      seg('s1', 'quiet'),
      text(' kingdom by the sea, there lived a '),
      seg('s2', 'baker'),
      text(' who dreamed of nothing but '),
      seg('s3', 'adventure'),
      text('. Every morning, the baker would '),
      seg('s4', 'wander'),
      text(' through the castle halls, humming a tune about '),
      seg('s5', 'the ocean'),
      text('. The king, a wise but '),
      seg('s6', 'strict'),
      text(' man, had only one rule: never '),
      seg('s7', 'open the gates'),
      text(' after midnight. But one fateful night, everything changed when a '),
      seg('s8', 'mysterious'),
      text(' stranger arrived carrying a '),
      seg('s9', 'lantern'),
      text(' and whispering about '),
      seg('s10', 'the future'),
      text('.'),
    ],
  },
  {
    id: 'nature-doc',
    parts: [
      text('Deep within the '),
      seg('s1', 'dense'),
      text(' forest, the '),
      seg('s2', 'gray wolf'),
      text(' begins its nightly search for '),
      seg('s3', 'food'),
      text('. It moves with '),
      seg('s4', 'silent'),
      text(' precision, guided by an instinct passed down for '),
      seg('s5', 'thousands of years'),
      text('. Nearby, a group of '),
      seg('s6', 'curious'),
      text(' rabbits watch from the '),
      seg('s7', 'undergrowth'),
      text(', unaware that tonight will end in '),
      seg('s8', 'a narrow escape'),
      text('. As the moon rises over the '),
      seg('s9', 'valley'),
      text(', the forest falls '),
      seg('s10', 'still'),
      text(', holding its breath for what comes next.'),
    ],
  },
  {
    id: 'instruction-manual',
    parts: [
      text('Step one: remove the '),
      seg('s1', 'protective cover'),
      text(' and place the device on a '),
      seg('s2', 'flat surface'),
      text('. Step two: connect the '),
      seg('s3', 'blue cable'),
      text(' to the port labeled '),
      seg('s4', 'POWER'),
      text('. Do not touch the '),
      seg('s5', 'metal contacts'),
      text(' while the unit is '),
      seg('s6', 'charging'),
      text('. Once the light turns '),
      seg('s7', 'green'),
      text(', press and hold the '),
      seg('s8', 'start button'),
      text(' for '),
      seg('s9', 'three seconds'),
      text('. If the device begins to '),
      seg('s10', 'beep rapidly'),
      text(', unplug it immediately.'),
    ],
  },
  {
    id: 'news-report',
    parts: [
      text('Local officials confirmed today that the '),
      seg('s1', 'annual festival'),
      text(' will proceed as planned despite concerns over '),
      seg('s2', 'the weather'),
      text(". Organizers say this year's event will feature a "),
      seg('s3', 'pie-eating contest'),
      text(', a performance by the '),
      seg('s4', 'high school band'),
      text(', and a raffle for '),
      seg('s5', 'a new bicycle'),
      text('. Mayor '),
      seg('s6', 'Jonathan Reyes'),
      text(' urged residents to arrive '),
      seg('s7', 'early'),
      text(' and expect '),
      seg('s8', 'heavy traffic'),
      text(' near '),
      seg('s9', 'Main Street'),
      text('. The festival begins at '),
      seg('s10', 'nine in the morning'),
      text(' and runs until sundown.'),
    ],
  },
]
