// Deliberately neutral — the "Good" or "Evil" spin is randomized separately at round start,
// so the same topic plays differently from game to game. Organized into categories so the
// host can pick a vibe for the group (or leave it on Random) before the round starts.
export const CATEGORIES = [
  {
    id: 'classic',
    label: 'Classic',
    topics: [
      "You just inherited your great-aunt's house",
      'Your coworker brought donuts to the office today',
      'You matched with someone new on a dating app',
      'Your neighbor started a compost pile right by your fence',
      'You got put in charge of planning the office party',
      'Your flight got upgraded to first class',
      'You found a twenty dollar bill in an old coat pocket',
      'Your roommate adopted a cat without asking you',
      'You were added to a group chat with your in-laws',
      'Your car started making a strange new noise',
      'You got a surprise phone call from an ex',
      'Your package arrived three days early',
      'You were asked to give a toast at a wedding',
      'Your favorite show got renewed for another season',
      'You found out your neighbor is a minor celebrity',
      'Your boss scheduled a mandatory weekend team retreat',
      'You won a gift card in the office raffle',
      'Your childhood best friend is moving in next door',
      'You got tagged in a photo from ten years ago',
      'Your landlord announced the building is being sold',
      'You were picked as designated driver again',
      'Your sibling asked to borrow a large sum of money',
      "You got invited to your ex's wedding",
      'Your smart speaker started talking back to you',
      'You found a mysterious locked box in the attic',
      'Your parents are visiting for two whole weeks',
      'You got promoted to manage your former peers',
      'Your identical twin started dating your best friend',
      'You were seated next to a celebrity on a long flight',
      'Your dog figured out how to open the fridge',
      'You accidentally replied-all to a company-wide email',
      'Your best friend wants to start a business with you',
      'You were handed the aux cord for the whole road trip',
    ],
  },
  {
    id: 'pop',
    label: 'Pop Culture',
    topics: [
      'You just went viral for the wrong reasons',
      'Your favorite show got cancelled after one season',
      "You're the newest member of a boy band",
      'Your karaoke video got ten million views overnight',
      "You're the face of a brand-new energy drink",
      'A celebrity liked your comment',
      'You started a dance trend by accident',
      'Your group chat meme made it onto the news',
      "You're this week's main character of the internet",
      'Your streaming account got hacked and someone posted your watch history',
      "You're the mystery guest on a TV singing competition",
      'Your fan theory turned out to be completely right',
    ],
  },
  {
    id: 'edgy',
    label: 'Edgy',
    topics: [
      "You're the reason the group project got an F",
      'You unfollowed your best friend during an argument',
      'You told a white lie that spiraled out of control',
      "You're the office's biggest conspiracy theorist",
      'You ghosted someone after one date',
      "You're the reason the family group chat got muted",
      "You said 'no offense' right before something offensive",
      "You're the villain in someone else's story",
      "You crashed a wedding you weren't invited to",
      'You started a rumor just to see what would happen',
      'You showed up late to your own surprise party',
      'You won an argument you knew you were wrong about',
    ],
  },
  {
    id: 'dark',
    label: 'Dark',
    topics: [
      'You wrote your own eulogy for fun',
      "You're the last one standing in a zombie apocalypse drill",
      'Your houseplant died and you held a funeral for it',
      'You found a suspicious note inside your fortune cookie',
      'Your horoscope predicted something oddly specific',
      "You're haunted by a mildly annoying ghost",
      "Your 'lucky number' turned out to be cursed the whole time",
      "You're the villain's reluctant sidekick",
      'Your near-death experience was extremely anticlimactic',
      "You're planning your own retirement party at age twenty-five",
      'You accidentally became the leader of a doomsday prepper group',
      'Your palm reader went suspiciously quiet halfway through',
    ],
  },
  {
    id: 'raunchy',
    label: 'Raunchy',
    topics: [
      'Your dating app date showed up in a full-body mascot costume',
      'You accidentally sent a flirty text to the group chat',
      'Your love language is unsolicited back massages',
      'You got caught practicing your wedding vows in the mirror',
      "Your ex just texted 'you up?' at 2pm on a Tuesday",
      'You matched with your coworker on a dating app',
      'You wrote a steamy novel under a pen name',
      "Your neighbors think you're 'that' couple",
      'You gave a wedding toast that got a little too honest',
      "You're the reason the honeymoon suite has a reputation",
      'You got caught sending a few too many heart-eye emojis',
      'Your slow-dance at the wedding lasted a song too long',
    ],
  },
  {
    id: 'stupid',
    label: 'Stupid',
    topics: [
      'You tried to pet every dog on your street in one day',
      'You built a blanket fort so elaborate it needs a mortgage',
      'You lost a staring contest with a pigeon',
      "You're convinced cereal is a soup",
      'You tried to microwave a burrito wrapped in foil',
      'You gave your Roomba a name and a whole personality',
      'You argued with your GPS out loud',
      'You tried to parallel park for twenty straight minutes',
      "You're the reason the vending machine is now empty",
      'You once ran away from a butterfly',
      'You tried to use a leaf as an umbrella',
      'You explained a movie plot completely wrong for a year',
    ],
  },
  {
    id: 'wholesome',
    label: 'Wholesome',
    topics: [
      'You left an extra-generous tip for a stressed-out waiter',
      'You taught your grandma how to video call',
      'You returned a lost wallet with all the cash still inside',
      "You organized a surprise party for a coworker's retirement",
      'You adopted the oldest dog at the shelter',
      'You wrote thank-you notes to your childhood teachers',
      'You started a free little library on your street',
      'You paid for the coffee of the person behind you in line',
      'You spent your birthday volunteering instead of celebrating',
      'You reunited a lost cat with its family',
      'You learned sign language just to talk to one coworker',
      'You planted a tree for every year of your life so far',
    ],
  },
  {
    id: 'petty',
    label: 'Petty',
    topics: [
      'You rearranged the office supplies out of spite',
      'You unfollowed someone over a lukewarm birthday message',
      'You kept score of who paid for lunch last, for years',
      'You gave someone the silent treatment over a parking spot',
      "You 'accidentally' left someone off the group invite",
      'You wore the same outfit as your rival on purpose',
      'You saved a petty text draft for three years without sending it',
      'You beat your sibling at a board game and never let them forget it',
      'You made a whole playlist just to vague-post about someone',
      'You returned a borrowed item in slightly worse condition on purpose',
      'You refused to be the one to text first for an entire month',
      'You corrected someone in a meeting just to make a point',
    ],
  },
  {
    id: 'chaotic',
    label: 'Chaotic',
    topics: [
      'You organized a flash mob with zero warning',
      'You brought a live chicken to a potluck',
      'You started a conga line during a fire drill',
      'You challenged a stranger to a dance-off',
      'You turned a quick grocery run into an accidental road trip',
      'You replied-all with a meme during a serious meeting',
      'You crowd-surfed at a library event',
      'You showed up to a costume party in entirely the wrong era',
      'You started a group chat war over pizza toppings',
      'You improvised an entire wedding speech with zero prep',
      'You turned a Tuesday into an impromptu holiday',
      'You convinced an entire bus to sing along with you',
    ],
  },
]

export function topicPool(categoryId) {
  if (!categoryId || categoryId === 'random') {
    return CATEGORIES.flatMap((c) => c.topics)
  }
  return CATEGORIES.find((c) => c.id === categoryId)?.topics ?? CATEGORIES.flatMap((c) => c.topics)
}
