// Deliberately neutral — the "Good" or "Evil" spin is randomized separately at round start,
// so the same topic plays differently from game to game.
export const TOPICS = [
  "You just inherited your great-aunt's house",
  'Your coworker brought donuts to the office today',
  'You matched with someone new on a dating app',
  'Your neighbor started a compost pile right by your fence',
  'You got put in charge of planning the office party',
  'Your flight got upgraded to first class',
  'You found a twenty dollar bill in an old coat pocket',
  'Your roommate adopted a cat without asking you',
  'You were added to a group chat with your in-laws',
  'Your car started making a strange new noise',
  'You got a surprise phone call from an ex',
  'Your package arrived three days early',
  'You were asked to give a toast at a wedding',
  'Your favorite show got renewed for another season',
  'You found out your neighbor is a minor celebrity',
  'Your boss scheduled a mandatory weekend team retreat',
  'You won a gift card in the office raffle',
  'Your childhood best friend is moving in next door',
  'You got tagged in a photo from ten years ago',
  'Your landlord announced the building is being sold',
  'You were picked as designated driver again',
  'Your sibling asked to borrow a large sum of money',
  'You got invited to your ex\'s wedding',
  'Your smart speaker started talking back to you',
  'You found a mysterious locked box in the attic',
  'Your parents are visiting for two whole weeks',
  'You got promoted to manage your former peers',
  'Your identical twin started dating your best friend',
  'You were seated next to a celebrity on a long flight',
  'Your dog figured out how to open the fridge',
  'You accidentally replied-all to a company-wide email',
  'Your best friend wants to start a business with you',
  'You were handed the aux cord for the whole road trip',
]
